config/routes.rb
Rails.application.routes.draw do
	root "welcome#index"
	devise_for :admins
	resources :admins
	resources "entries"
	get "about", to: "welcome#about"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable, :timeoutable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
	has_one_attached :media
	has_many :taggings
	has_many :tags, through: :taggings

	#media.attach(params[:media])
	
	def self.entry_tagged_with(tag)
		Tag.find_by(name: tag).entries
	end
	def self.tag_counts
		Tag.select('tags.*, count(taggings.tag_id) as
			count').joins(:taggings).group('taggings.tag_id')
	end
	def self.tags_on_entry(entry_id)
		Tag.where(id: Entry.find_by_id(entry_id).tag_ids)
	end
	def all_tags=(names)
	  self.tags = names.split(",").map do |name|
	      Tag.where(name: name.strip).first_or_create!
    	end
    end
	def all_tags
	  self.tags.map(&:name).join(", ")
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :entries, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :entry
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #    super
  #  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController	
	def index
		@entries = Entry.order(date: :desc).entry_tagged_with(params[:tag]).paginate(page: params[:page], per_page: 5)
	end
	def create
		entry_params = params["entry"].permit("title", "date","contents", "all_tags", "media")
		entry = Entry.create(entry_params)
		redirect_to(entry_path(entry))
	end
	def show
		@entry = Entry.find(params["id"])
		@tags = Entry.tags_on_entry(params["id"])
	end
	def edit 
		@entry = Entry.find(params["id"])
		@tags = Entry.tags_on_entry(params["id"])
	end
	def update
		entry_params = params["entry"].permit("title", "date", "contents", "all_tags", "media")
		entry = Entry.find(params["id"])
		entry.update(entry_params)
		redirect_to(entry_path(entry))
	end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
		options = [:highlight, :tables,:hard_wrap, :autolink, :no_intra_emphasis, :fenced_code_block, :underline]
		Markdown.new(text, *options).to_html.html_safe
	end
	
	def title(page_title)
 	 content_for(:title) { page_title }
	end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<% title "Editing #{@entry.title}" %>
<div class="row">
	<div class="col-md-3">
	</div>
	<div class="col-md-6">
		<%= form_for(@entry) do |form| %>
			<div class="post-form">
				<div class= "field form-group">
					<h3><%= form.label :title %></h3>
					<p><%= form.text_field :title, class: 'form-control' %></p>
				</div>
				<div class= "field form-group">
					<h3><%= form.label :date %></h3>
					<p><%= form.date_field :date, class: 'form-control', placeholder: 'MM/DD/YYYY' %></p>
				</div>
				<div class= "field form-group">
					<h3><%= form.label :contents %></h3>
					<p><%= form.text_area :contents, class: 'form-control' %></p>
				</div>
				<div class= "field form-group">
					<h3><%= form.label :all_tags %></h3>
					<p><%= form.text_field :all_tags, class: 'form-control' %></p>
				</div>
				<div class= "field form-group">
					<h3><%= form.label :media %></h3>
					<p><%= form.file_field :media, class: 'form-control' %></p>
				</div>
				<div class= "action form-group">
					<%= form.submit class: 'btn btn-primary' %>
				</div>
				<br>
				<%= link_to("Back to this entry", entry_path(@entry), class: "btn btn-danger") %>
			</div>
		<% end %>
	</div>
	<div class="col-md-3">
	</div>
</div>

app/views/entries/index.html.erb
<% title params[:tag] %>
<% for entry in  @entries %>
	<div class="row">
    	<div class="col-md-10 offset-md-1 card card-body bg-light">
            <h1><%= link_to(entry.title, entry_path(entry)) %></h1>
            <div class="entry">
                <div class="col-md-3">
                <% if entry.media.attached? %>
                    <image src="<%=(url_for(entry.media)) %>" class="img-thumbnail">
                <% end %>
            </div>

            <div class="col-md-5">
                <% if entry.contents.length >=145 %>
                    <%= markdown("#{entry.contents[0,144]}...") %>
                    <%= link_to("See more", entry_path(entry)) %>
                <% else %>
                    <%= markdown(entry.contents) %>
                <% end %>
            </div>
            <div class="col-md-2">
                <h6><%= entry.date %></h6>
            </div>
            <div class="col-md-2">
                <h6><%= entry.all_tags%></h6>
            </div>
        	</div>
        	
        	<% if admin_signed_in? %>  
        	   <div class="col-md-1">      
        		  <%= link_to("Edit", edit_entry_path(entry), class: 'btn btn-warning') %>
                </div>
            <% end %>
    	</div>
    </div>
    <br>
<% end %>

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="page_info">
      <%= page_entries_info @entries %>
    </div>
    <div>
         <%= will_paginate @entries, :container => false %>
    </div>
  </div>




app/views/entries/new.html.erb
<% title "New Post" %>
	<div class="row">
		<div class="col-md-3">
		</div>
		<div class="col-md-6">
			<%= form_for(Entry.new) do |form| %>
				<div class="post-form">
					<div class= "field form-group">
						<h3><%= form.label :title %></h3>
						<p><%= form.text_field :title, class: 'form-control' %></p>
					</div>
					<div class= "field form-group">
						<h3><%= form.label :date %></h3>
						<p><%= form.date_field :date, class: 'form-control', placeholder: 'MM/DD/YYYY' %></p>
					</div>
					<div class= "field form-group">
						<h3><%= form.label :contents %></h3>
						<p><%= form.text_area :contents, class: 'form-control' %></p>
					</div>
					<div class= "field form-group">
						<h3><%= form.label :tags %></h3>
						<p><%= form.text_field :all_tags, class: 'form-control' %></p>
					</div>
					<div class= "field form-group">
						<h3><%= form.label :media %></h3>
						<p><%= form.file_field :media, class: 'form-control' %></p>
					</div>
					<div class= "action form-group">
						<%= form.submit class: 'btn btn-primary' %>
					</div>

				</div>
			<% end %>
		</div>
	<div class="col-md-3">
	</div>
</div>




app/views/entries/show.html.erb
<% title @entry.date.to_s %>
<div class="row">
	<div class="col-md-10 offset-md-1 card card-body bg-light show-entry">
		<h1><%= @entry.title %></h1>
		<% if @entry.media.attached? %>
			<image src="<%=(url_for(@entry.media)) %>" class="entry-image">
		<% end %>	
		<div>
			<p class="text-wrap"> <%= markdown(@entry.contents)%> </p>
		</div>
	</div>
	<% if admin_signed_in? %>  
	    	   <div class="col-md-1">      
	    		  <%= link_to("Edit", edit_entry_path(@entry.id), class: 'btn btn-warning') %>
	            </div>
	<% end %>
	<br>
	<div class="col-md-4 offset-md-1">
		<h5> Back to Category:</h5>
		<% for tag in @tags %>
			<%= link_to tag.name, entries_path(:tag =>  tag.name), class:"btn btn-light" %></a>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jacob Eekhof</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "https://emoji.gg/assets/emoji/1132_dancingcat.gif" %>
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
   <script src="https://kit.fontawesome.com/f64ecfb92d.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <nav id= "mySideNav" class="sidenav navbar-expand-md navbar-dark">
        <div>
          <%= link_to "Jacob Eekhof", root_path , class:"brand"%>
          <br>
          <i class="fas fa-gamepad"></i>
        </div>
        
        <div>    
          <%= link_to "Work ", entries_path(:tag => "work"), class:"nav-link" %></a>
          <%= link_to "Study ", entries_path(:tag => "study"), class:"nav-link" %></a>
          <%= link_to "Play ", entries_path(:tag => "play"), class:"nav-link" %></a>
        </div>
        <div>
          <%= link_to "About", about_path, class:"nav-link" %></a>
          <div class="social-links"> 
             <a href="https://github.com/jdeekhof", target="_new"><i class="fab fa-github"></i></a>
             <a href="https://discord.com/users/571151209231155201", target="_new"><i class="fab fa-discord"></i></i></a>
             <a href="mailto:jdeekhof@gmail.com", target="_new"><i class="fas fa-envelope-open-text"></i></a>
             <a href="https://www.linkedin.com/in/jacobeekhof/", target="_new"><i class="fab fa-linkedin-in"></i></a>
          </div>
        </div>
      </nav>
      <div class='main' id="main">
        <nav class="navbar navbar-dark bg-black">
          <div class="menuToggler open" onclick="iconAnimate(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
          </div>
          <div>
            <h2 class="text-white"> 
              <%= content_for?(:title) ? content_for(:title) : "Jacob Eekhof" %> 
            </h2>
          </div>
            <% if admin_signed_in? %>
              <div>
                <%= link_to("New Post", new_entry_path, class: 'btn btn-primary') %>
                <%= link_to "Log Out", destroy_admin_session_path, method: :delete, class:"btn btn-danger" %>
              </div>
            <% else %>
              <%= link_to "Log In", new_admin_session_path, class:"btn btn-success" %>
            <% end %>
          </nav> 
        <div class='container content'>
          <div class="container">
            <% flash.each do |type, msg| %>
            <% if type == "notice" %>
              <%= content_tag :div, msg, class: "alert alert-success" %>
            <% elsif type == "alert" %>
              <%= content_tag :div, msg, class: "alert alert-danger" %>
              <% end %>
            <% end %>
          </div>
          <%= yield %>
        </div>
      </div>

  <script type="text/javascript">
    window.onload = initializeSideNav()
    
    function initializeSideNav() {
      if (window.localStorage.sideNavState == null) {
        console.log("hi")
        setNav("250px")
        localStorage.setItem("sideNavState", "250px")
      }
      else {
        setNav(window.localStorage.sideNavState)
        console.log("bye")
      }
    }

    function setNav(s) {
      nav =  document.getElementById('mySideNav')
      main = document.getElementById('main')
      nav.style.width = s
      main.style.marginLeft = s
    }
  
    function iconAnimate(x) {
        if (window.localStorage.sideNavState == "250px"){
          x.classList.toggle("open");
          localStorage.setItem("sideNavState", 0)
          setNav(window.localStorage.sideNavState)
          console.log(window.localStorage.sideNavState)
        }
        else{
          x.classList.toggle("open")
          localStorage.setItem("sideNavState", "250px")
          setNav(window.localStorage.sideNavState)
          console.log(window.localStorage.sideNavState)
        }
    }

  </script>
  </body>
</html>

app/views/welcome/about.html.erb
<%- title "About me" %>
<div class="row">
	<div class="col-md-10 offset-md-1 card card-body bg-light show-entry">
		<a href="https://karrraska.tumblr.com/" target="_blank"><img class="entry-image" src="https://res.cloudinary.com/dqbibdsz3/image/upload/v1612816499/reddit/1537c5ec287fed4ec59a981ece60fc28b67a4849_amrwrp.jpg"></a>
    	<p class="text-wrap">
    		<h5>Howdy,</h5> my name's Jacob if you haven't already figured that out. My last name is Dutch and its techinically pronounced a-cough, but most folks just say eeeek-off. I identify as he/him, and currently work for a tech startup called <a href="https://dockwa.com">Dockwa</a> as a technical support analyst. I went to Salve Regina University for Economics and philosophy, but I've found a passion for coding and datascience since leaving. Absurdly curious with a proclivity for math and logic. I enjoy wading into problems and forming systems. If I'm not learning and thinking about projects for work, I'm probably doing the same thing in games, or finding new music, or walking the dog, or sleeping (least likely). Reach me on any of the icons on that fancy sidenav if you have questions or want to talk.
    	</p>
	</div>
    
  
</div>

app/views/welcome/contact.html.erb

<p>
		You can check out more of my projects on <a href="https://github.com/jdeekhof", target="_new">Github.</a> To get in contact send me an email at <a href="mailto:jdeekhof@gmail.com", target="_new">jdeekhof@gmail.com</a>, add me on <a href="https://www.linkedin.com/in/jacobeekhof/", target="_new">LinkedIn</a>, or preferably message me on <a href="https://discord.com/users/571151209231155201", target="_new">Discord</a>.
</p>

app/views/welcome/index.html.erb
  <div class="row">

    <div class="col-md-4">
     
    </div>

    

    <div class="col-md-4">
      <br>
       <h1>Welcome,</h1>
       <p> This site was created to practice <a href="https://rubyonrails.org/">Ruby on Rails</a> and various other web development tools. I tried to make it a bit more interesting than using wordpress. Let me know what you think.</p>
    </div>
    
  </div>



	